from app.models import db, Ingredient

# Adds a demo user, you can add other users here if you want


def seed_ingredients():

    demo = Ingredient(name="Graham Cracker", type_id=1)
    demo1 = Ingredient(name="Sugar", type_id=1)
    demo2 = Ingredient(name="Salt", type_id=2)
    demo3 = Ingredient(name="Unsalted Butter", type_id=3)
    demo4 = Ingredient(name="Melted Unsalted Butter", type_id=3)
    demo5 = Ingredient(name="Salted Butter", type_id=3)
    demo6 = Ingredient(name="Melted Salted Butter", type_id=3)
    demo7 = Ingredient(name="Gelatin", type_id=1)
    demo8 = Ingredient(name="Cinnamon", type_id=2)
    demo9 = Ingredient(name="Nutmeg", type_id=2)
    demo10 = Ingredient(name="Egg", type_id=3)
    demo11 = Ingredient(name="Egg Yolk", type_id=3)
    demo12 = Ingredient(name="Egg White", type_id=3)
    demo13 = Ingredient(name="Milk", type_id=3)
    demo14 = Ingredient(name="Whole Milk", type_id=3)
    demo15 = Ingredient(name="2% Milk", type_id=3)
    demo16 = Ingredient(name="Unsweetened Pumpkin Purée", type_id=1)
    demo17 = Ingredient(name="Heavy Cream", type_id=3)
    demo18 = Ingredient(name="Flour", type_id=1)
    demo19 = Ingredient(name="Rolled Oats", type_id=1)
    demo20 = Ingredient(name="White Rice", type_id=1)
    demo21 = Ingredient(name="Brown Rice", type_id=1)
    demo22 = Ingredient(name="Spaghetti Noodles", type_id=1)
    demo23 = Ingredient(name="Vegetable Oil", type_id=1)
    demo24 = Ingredient(name="Olive Oil", type_id=1)
    demo25 = Ingredient(name="Honey", type_id=1)
    demo26 = Ingredient(name="Peanut Butter", type_id=1)
    demo27 = Ingredient(name="Sour Cream", type_id=3)

    demo28 = Ingredient(name="Oregano", type_id=2)
    demo29 = Ingredient(name="Basil", type_id=2)
    demo30 = Ingredient(name="Thyme", type_id=2)
    demo31 = Ingredient(name="Cumin", type_id=2)
    demo32 = Ingredient(name="Crushed Red Pepper", type_id=2)
    demo33 = Ingredient(name="Cayenne Pepper", type_id=2)
    demo34 = Ingredient(name="Smoked Paprika", type_id=2)
    demo35 = Ingredient(name="Cinnamon", type_id=2)
    demo36 = Ingredient(name="Curry Powder", type_id=2)
    demo37 = Ingredient(name="Chili Powder", type_id=2)
    demo38 = Ingredient(name="Garlic Powder", type_id=2)
    demo39 = Ingredient(name="Cocoa Powder", type_id=2)
    demo40 = Ingredient(name="Vanilla Extract", type_id=2)
    demo41 = Ingredient(name="Turmeric", type_id=2)

    demo42 = Ingredient(name="Baking Powder", type_id=1)
    demo43 = Ingredient(name="Baking Soda", type_id=1)

    demo44 = Ingredient(name="Ribeye Steak", type_id=6)
    demo45 = Ingredient(name="Rib Roast", type_id=6)
    demo46 = Ingredient(name="Flank Steak", type_id=6)
    demo47 = Ingredient(name="T-Bone Steak", type_id=6)
    demo48 = Ingredient(name="Back Ribs", type_id=6)
    demo49 = Ingredient(name="Ground Beef", type_id=6)

    demo50 = Ingredient(name="Chicken Breast", type_id=6)
    demo51 = Ingredient(name="Chicken Thigh", type_id=6)
    demo52 = Ingredient(name="Chicken Leg", type_id=6)
    demo53 = Ingredient(name="Pork Tenderloin", type_id=6)
    demo54 = Ingredient(name="Pork Chop", type_id=6)
    demo55 = Ingredient(name="Baby Back Ribs", type_id=6)
    demo56 = Ingredient(name="Ground Pork", type_id=6)
    demo57 = Ingredient(name="Wild Salmon", type_id=6)
    demo58 = Ingredient(name="Wild Halibut", type_id=6)
    demo59 = Ingredient(name="Shrimp", type_id=6)

    demo60 = Ingredient(name="Apple", type_id=7)
    demo61 = Ingredient(name="Pear", type_id=7)
    demo62 = Ingredient(name="Banana", type_id=7)
    demo63 = Ingredient(name="Garlic Clove", type_id=2)
    demo64 = Ingredient(name="Fresh Parsley", type_id=2)
    demo65 = Ingredient(name="Fresh Cilantro", type_id=2)
    demo66 = Ingredient(name="Fresh Dill", type_id=2)
    demo67 = Ingredient(name="Fresh Basil", type_id=2)
    demo68 = Ingredient(name="Fresh Rosemary", type_id=2)
    demo69 = Ingredient(name="Lemon", type_id=7)
    demo70 = Ingredient(name="Lime", type_id=7)
    demo71 = Ingredient(name="Watermelon", type_id=7)
    demo72 = Ingredient(name="Strawberry", type_id=7)
    demo73 = Ingredient(name="Asparagus", type_id=7)
    demo74 = Ingredient(name="Cabbage", type_id=7)
    demo75 = Ingredient(name="Potato", type_id=7)
    demo76 = Ingredient(name="Tomato", type_id=7)
    demo77 = Ingredient(name="Zucchini", type_id=7)
    demo78 = Ingredient(name="Carrot", type_id=7)
    demo79 = Ingredient(name="Broccoli", type_id=7)
    demo80 = Ingredient(name="Cauliflower", type_id=7)
    demo81 = Ingredient(name="Yellow Onion", type_id=7)
    demo82 = Ingredient(name="White Onion", type_id=7)
    demo83 = Ingredient(name="Lasagna Noodles", type_id=1)
    demo84 = Ingredient(name="Peas", type_id=7)
    demo85 = Ingredient(name="Cremini Mushroom", type_id=7)
    demo86 = Ingredient(name="Portobello Mushroom", type_id=7)
    demo87 = Ingredient(name="Soy Sauce", type_id=2)
    demo88 = Ingredient(name="Worcestershire", type_id=2)
    demo89 = Ingredient(name="Yellow Mustard", type_id=2)
    demo90 = Ingredient(name="Dijon Mustard", type_id=2)
    demo91 = Ingredient(name="Orange Juice", type_id=5)
    demo92 = Ingredient(name="Red Wine", type_id=5)
    demo93 = Ingredient(name="White Wine", type_id=5)
    demo94 = Ingredient(name="Whiskey", type_id=5)
    demo95 = Ingredient(name="Vodka", type_id=5)
    demo96 = Ingredient(name="Rum", type_id=5)
    demo97 = Ingredient(name="Tequila", type_id=5)
    demo98 = Ingredient(name="Cognac", type_id=5)
    demo99 = Ingredient(name="Beer", type_id=5)
    demo100 = Ingredient(name="Champagne", type_id=5)
    demo101 = Ingredient(name="Rose", type_id=5)
    demo102 = Ingredient(name="Water", type_id=5)
    demo103 = Ingredient(name="Ketchup", type_id=2)

    db.session.add(demo)
    db.session.add(demo1)
    db.session.add(demo2)
    db.session.add(demo3)
    db.session.add(demo4)
    db.session.add(demo5)
    db.session.add(demo6)
    db.session.add(demo7)
    db.session.add(demo8)
    db.session.add(demo9)
    db.session.add(demo10)
    db.session.add(demo11)
    db.session.add(demo12)
    db.session.add(demo13)
    db.session.add(demo14)
    db.session.add(demo15)
    db.session.add(demo16)
    db.session.add(demo17)
    db.session.add(demo18)
    db.session.add(demo19)
    db.session.add(demo20)
    db.session.add(demo21)
    db.session.add(demo22)
    db.session.add(demo23)
    db.session.add(demo24)
    db.session.add(demo25)
    db.session.add(demo26)
    db.session.add(demo27)
    db.session.add(demo28)
    db.session.add(demo29)
    db.session.add(demo30)
    db.session.add(demo31)
    db.session.add(demo32)
    db.session.add(demo33)
    db.session.add(demo34)
    db.session.add(demo35)
    db.session.add(demo36)
    db.session.add(demo37)
    db.session.add(demo38)
    db.session.add(demo39)
    db.session.add(demo40)
    db.session.add(demo41)
    db.session.add(demo42)
    db.session.add(demo43)
    db.session.add(demo44)
    db.session.add(demo45)
    db.session.add(demo46)
    db.session.add(demo47)
    db.session.add(demo48)
    db.session.add(demo49)
    db.session.add(demo50)
    db.session.add(demo51)
    db.session.add(demo52)
    db.session.add(demo53)
    db.session.add(demo54)
    db.session.add(demo55)
    db.session.add(demo56)
    db.session.add(demo57)
    db.session.add(demo58)
    db.session.add(demo59)
    db.session.add(demo60)
    db.session.add(demo61)
    db.session.add(demo62)
    db.session.add(demo63)
    db.session.add(demo64)
    db.session.add(demo65)
    db.session.add(demo66)
    db.session.add(demo67)
    db.session.add(demo68)
    db.session.add(demo69)
    db.session.add(demo70)
    db.session.add(demo71)
    db.session.add(demo72)
    db.session.add(demo73)
    db.session.add(demo74)
    db.session.add(demo75)
    db.session.add(demo76)
    db.session.add(demo77)
    db.session.add(demo78)
    db.session.add(demo79)
    db.session.add(demo80)
    db.session.add(demo81)
    db.session.add(demo82)
    db.session.add(demo83)
    db.session.add(demo84)
    db.session.add(demo85)
    db.session.add(demo86)
    db.session.add(demo87)
    db.session.add(demo88)
    db.session.add(demo89)
    db.session.add(demo90)
    db.session.add(demo91)
    db.session.add(demo92)
    db.session.add(demo93)
    db.session.add(demo94)
    db.session.add(demo95)
    db.session.add(demo96)
    db.session.add(demo97)
    db.session.add(demo98)
    db.session.add(demo99)
    db.session.add(demo100)
    db.session.add(demo101)
    db.session.add(demo102)
    db.session.add(demo103)

    db.session.commit()

# Uses a raw SQL query to TRUNCATE the recipe table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key


def undo_ingredients():
    db.session.execute('TRUNCATE ingredients RESTART IDENTITY CASCADE;')
    db.session.commit()
