"""create_cooking_lists_table

Revision ID: 808078b7668f
Revises: 27ca2257c283
Create Date: 2021-01-05 20:07:24.623864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808078b7668f'
down_revision = '27ca2257c283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooking_lists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cooking_lists')
    # ### end Alembic commands ###
